### Development ###
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    container_name: ghost-bunnycdn-connector-dev
    expose:
      - 3000/tcp
    ports:
      - "3000:3000"
    environment:
      - TZ=Etc/UTC
    env_file:
      - .env
    volumes:
      - ./runtime-data:/data
    networks:
      - development


### Networks ###
networks:
  development:
    driver: bridge
